version: '3'
services:
  #Mysql service
  mysql:
    image: 'mysql:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=passer
      - MYSQL_DATABASE=adhesion
    ports:
      - "3307:3306"
  #Back-end Spring Boot Application
  microservice-adhesion:
    image: bibndiaye/microservice-adhesion
    ports:
      - "1234:1234"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/adhesion?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
      # build:
      #context: "./"
      #dockerfile: "Dockerfile"
    depends_on:
      - mysql
#Front-end Angular Application
#  frontend:
#      build: ../cimrpoc-web/
#      links:
#             - "microservice-adhesion"
#      depends_on:
#             - "microservice-adhesion"
#      ports:
#             - "81:80" 
