server:
  servlet:
    context-path: /adhesion
  port: 1234
    
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://mysql:3306/adhesion?allowPublicKeyRetrieval=true&useSSL=false           #docker config
        #url: jdbc:mysql://mysql-service:3306/adhesion?allowPublicKeyRetrieval=true&useSSL=false  #k8s config
        username: root
        password: admin     
    jpa:
        database-platform: org.hibernate.dialect.MySQL5Dialect
        generate-ddl: true
        show-sql: true
        hibernate:
            ddl-auto: update  
  


    